apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: object-detection-rest-k6em
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: object-detection-rest-k6em
    app.kubernetes.io/part-of: object-detection-rest
  name: object-detection-rest-k6em
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: object-detection-rest-k6em
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: object-detection-rest-k6em
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/mfaisal2-tenant/object-detection-rest/object-detection-rest-k6em@sha256:c992674ac85a07d177431fc5472b41f3e6dab354b9dfe23c4bcde007d2f70159
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
