apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: object-detection-rest-k6em
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: object-detection-rest-k6em
    app.kubernetes.io/part-of: object-detection-rest
  name: object-detection-rest-k6em
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: object-detection-rest-k6em
status:
  loadBalancer: {}
