apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: object-detection-rest-k6em
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: object-detection-rest-k6em
    app.kubernetes.io/part-of: object-detection-rest
  name: object-detection-rest-k6em
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: object-detection-rest-k6em
    weight: null
status: {}
